# Generated by Django 4.1.6 on 2023-04-23 08:19

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_notification_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, upload_to=chat.models.chat_image_directory_path),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
