# Generated by Django 4.1.6 on 2023-04-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_last_logout_userinfo_online_status'),
        ('post', '0002_post_dislikes_post_likes_delete_like'),
        ('chat', '0006_alter_chat_file_alter_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='add_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.friend'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
