# Generated by Django 4.1.6 on 2023-04-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification_add_friend_notification_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='add_friend',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
