# Generated by Django 4.1.6 on 2023-04-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_delete_like'),
        ('user', '0005_userinfo_last_logout_userinfo_online_status'),
        ('chat', '0008_remove_notification_add_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='add_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.friend'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
