# Generated by Django 4.1.6 on 2023-04-24 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_delete_like'),
        ('user', '0006_merge_20230423_2244'),
        ('chat', '0009_notification_add_friend_notification_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='add_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.friend'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
