# Generated by Django 4.1.6 on 2023-04-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openChat', '0010_alter_message_file'),
        ('chat', '0011_notification_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='openchat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openChat.openchat'),
        ),
    ]
