# Generated by Django 4.2 on 2023-05-02 15:57

import chat.models
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_notification_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=django_cryptography.fields.encrypt(models.FileField(blank=True, upload_to=chat.models.chat_image_directory_path)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
    ]
