# Generated by Django 4.1.6 on 2023-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_friend_friend_id_alter_friend_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='online_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
