# Generated by Django 4.1.6 on 2023-04-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
