# Generated by Django 4.1.6 on 2023-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_notification'),
    ]

    operations = [
    ]
