# Generated by Django 4.1.6 on 2023-04-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_last_logout_userinfo_online_status'),
        ('user', '0005_userinfo_last_logout_userinfo_online_status'),
    ]

    operations = [
    ]
