# Generated by Django 4.2 on 2023-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20230423_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chatup_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
