# Generated by Django 4.1.6 on 2023-03-26 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openChat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openchat',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openchat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
