# Generated by Django 4.1.6 on 2023-04-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openChat', '0002_openchat_members_alter_openchat_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
    ]
