# Generated by Django 4.1.6 on 2023-04-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20230423_2244'),
        ('openChat', '0004_alter_openchat_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_created_by', to='user.userinfo'),
        ),
        migrations.AlterField(
            model_name='openchat',
            name='members',
            field=models.ManyToManyField(blank=True, to='user.userinfo'),
        ),
    ]
