# Generated by Django 4.1.6 on 2023-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openChat', '0005_alter_message_created_by_alter_openchat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='openchat',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
