# Generated by Django 4.1.6 on 2023-04-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openChat', '0008_alter_openchat_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openchat',
            name='group_image',
            field=models.ImageField(blank=True, default='./static/assets/default_profile_image/avatar.jpg', upload_to='uploads/'),
        ),
    ]
