# Generated by Django 4.1.6 on 2023-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openChat', '0009_alter_openchat_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='file_in_openchat/'),
        ),
    ]
