# Generated by Django 4.2 on 2023-05-02 15:57

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openChat', '0010_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=django_cryptography.fields.encrypt(models.FileField(blank=True, upload_to='file_in_openchat/')),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='openchat',
            name='group_image',
            field=models.ImageField(blank=True, default='./static/assets/default_profile_image/avatar.jpg', upload_to='file_in_openchat/'),
        ),
    ]
